CREATE SEQUENCE seq_pm_list      START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE seq_pm_list;
CREATE SEQUENCE seq_pm_question  START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE seq_pm_question;
CREATE SEQUENCE seq_visit_record START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE seq_visit_record;
CREATE SEQUENCE seq_visit_answer START WITH 1 INCREMENT BY 1 NOCACHE;
DROP SEQUENCE seq_visit_answer;
